### ISSUE TITLE
Error while writing SFS item

### ISSUE THREAD

**Issue by istern** [kamsar/Rainbow#16]
Maybe this i by design, I dont even know have the media item in question was created.

Trying to serialize via Unicorn the attach media item to disk gives the error below.

Sitecore version 8.1-update 1 Using Latest and greates Unicorn with Rainbow  from github.

[readmy_for_unicorn-1.0.0.0.zip](https://github.com/kamsar/Rainbow/files/442903/readmy_for_unicorn-1.0.0.0.zip)

Error occurs in
Rainbow.Storage.Yaml.OutputModel.YamlFieldValue in the write yaml methodsometime the value is null but o guard against, maybe by design, but everthing else in the method is well protected.

`ERROR: One or more errors occurred. (System.AggregateException)
at Unicorn.SerializationHelper.DumpTreeInternal(IItemData root, IPredicate predicate, ITargetDataStore serializationStore, ISourceDataStore sourceDataStore, ILogger logger) in C:\Projects\Unicorn\src\Unicorn\SerializationHelper.cs:line 225 
at Unicorn.SerializationHelper.DumpTree(IItemData item, IConfiguration[] configurations) in C:\Projects\Unicorn\src\Unicorn\SerializationHelper.cs:line 60 
at Unicorn.ControlPanel.Pipelines.UnicornControlPanelRequest.ReserializeVerb.Process(IProgressStatus progress, ILogger additionalLogger) in C:\Projects\Unicorn\src\Unicorn\ControlPanel\Pipelines\UnicornControlPanelRequest\ReserializeVerb.cs:line 67
Error while writing SFS item c:\Websites\sc81rev151207\Data\Unicorn\all\ml\media library\readme.yml (Rainbow.Storage.SfsWriteException)
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) in C:\Projects\Rainbow\src\Rainbow\Storage\SerializationFileSystemTree.cs:line 372 
at Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item) in C:\Projects\Rainbow\src\Rainbow\Storage\SerializationFileSystemTree.cs:line 295 
at Rainbow.Storage.SerializationFileSystemDataStore.Save(IItemData item) in C:\Projects\Rainbow\src\Rainbow\Storage\SerializationFileSystemDataStore.cs:line 50 
at Unicorn.Data.ConfigurationDataStore.Save(IItemData item) in C:\Projects\Unicorn\src\Unicorn\Data\ConfigurationDataStore.cs:line 26 
at Unicorn.SerializationHelper.DumpItemInternal(IItemData item, IPredicate predicate, ITargetDataStore targetDataStore) in C:\Projects\Unicorn\src\Unicorn\SerializationHelper.cs:line 232 
at Unicorn.SerializationHelper.<>c__DisplayClass8_0.b__1() in C:\Projects\Unicorn\src\Unicorn\SerializationHelper.cs:line 184
Object reference not set to an instance of an object. (System.NullReferenceException)
at Rainbow.Storage.Yaml.YamlWriter.WriteMapInternal(String key, String value) in C:\Projects\Rainbow\src\Rainbow.Storage.Yaml\YamlWriter.cs:line 62 
at Rainbow.Storage.Yaml.YamlWriter.WriteMap(String key, String value) in C:\Projects\Rainbow\src\Rainbow.Storage.Yaml\YamlWriter.cs:line 51 
at Rainbow.Storage.Yaml.OutputModel.YamlFieldValue.WriteYaml(YamlWriter writer) in C:\Projects\Rainbow\src\Rainbow.Storage.Yaml\OutputModel\YamlFieldValue.cs:line 57 
at Rainbow.Storage.Yaml.OutputModel.YamlItem.WriteYaml(YamlWriter writer) in C:\Projects\Rainbow\src\Rainbow.Storage.Yaml\OutputModel\YamlItem.cs:line 93 
at Rainbow.Storage.Yaml.YamlSerializationFormatter.WriteSerializedItem(IItemData itemData, Stream outputStream) in C:\Projects\Rainbow\src\Rainbow.Storage.Yaml\YamlSerializationFormatter.cs:line 92 
at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) in C:\Projects\Rainbow\src\Rainbow\Storage\SerializationFileSystemTree.cs:line 366

`

**Comment by istern** [comment]
Update in the LoadFrom in the YamlFieldValue you set Value to field.value which in this case is null, giving the above issue.

**Comment by istern** [comment]
Created a PR with the fix here
https://github.com/kamsar/Rainbow/pull/17

**Comment by kamsar** [comment]
Yeah Unicorn/Rainbow is touchy about null vs empty field values. There are places where they are not identical.

I will do some additional testing with your PR and sample item, but my initial thought would be to handle this at the output end as opposed to the input. It wouldn't surprise me if @cassidydotdk and I made this bug when we were working on some other null-vs-empty stuff in the latest RCs :)

**Comment by istern** [comment]
Perfect,I Intially tried doing just before the output was written, by just skippng the value line in yaml, but then the deserializer had some issues with missing entries so to as little invasive as possible i went for this solution. :)
