### ISSUE TITLE
Windows reserved file names

### ISSUE THREAD

**Issue by agehrke** [kamsar/Rainbow#8]
I had an item named CON and I could not understand why Unicorn failed to serialize the item. Unicorn failed with:

    Error while writing SFS item C:\mypath\Data\Unicorn\inRiver\Test\Home\CON.yml (Rainbow.Storage.SfsWriteException)
    at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path) 
    at Unicorn.SerializationHelper.DumpItemInternal(IItemData item, IPredicate predicate, ITargetDataStore targetDataStore) 
    at Unicorn.SerializationHelper.<>c__DisplayClass5.b__4()
      FileStream will not open Win32 devices such as disk partitions and tape drives. Avoid use of "\\.\" in the path. (System.ArgumentException)
      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) 
      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) 
      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) 
      at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path)

Turns out *CON* is a reserved filename on Windows:

    Do not use the following reserved names for the name of a file:
    CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

Source: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

I guess this should to be addressed in SFS?

**Comment by kamsar** [comment]
I will get this fixed, for all of the folks making websites that sell serial and parallel cables that use Sitecore ;)

Seriously though I'll roll it into the next release.

**Comment by kamsar** [comment]
Done. That wasn't too hard at all. Thanks for the issue report!

**Comment by agehrke** [comment]
Great, thanks :)
